site:
  title: fuquery
  start_page: _::index.adoc
output:
  dir: build
content:
  sources:
  - url: .
    start_paths: [.]
  - url: https://github.com/fuquery/rsl.git
    branches: docs
    start_path: docs
ui:
  bundle:
    url: ui
antora:
  extensions:
  - '@antora/lunr-extension'
  - '@antora/collector-extension'
